# Generated by Django 5.1 on 2024-09-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('interested', models.CharField(max_length=255)),
                ('move_by', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.IntegerField()),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('not', 'Not Invoiced'), ('pend', 'Pending'), ('over', 'Overdue'), ('paid', 'Paid')], default='not', max_length=25)),
                ('flat_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('move_date', models.DateField()),
                ('unit_no', models.CharField(max_length=255)),
                ('lease_term', models.CharField(max_length=255)),
                ('deal_date', models.DateField(auto_now_add=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('overdue_date', models.DateField(blank=True, null=True)),
                ('lease_end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_number', models.CharField(blank=True, max_length=20, null=True)),
                ('layout', models.CharField(blank=True, max_length=50, null=True)),
                ('sq_ft', models.CharField(blank=True, max_length=10, null=True)),
                ('available', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes / Specials')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trec', models.CharField(blank=True, null=True, unique=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
