# Generated by Django 5.1 on 2025-01-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='msg',
            field=models.TextField(default='Below is the guest card info for my client . Please let me know if there are any issues.'),
        ),
    ]
