# Generated by Django 5.1 on 2024-08-28 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_deal_agent_deal_client'),
        ('property', '0002_property_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='property.property'),
        ),
    ]
