# Generated by Django 5.1 on 2024-08-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_alter_card_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='available',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='layout',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes / Specials'),
        ),
        migrations.AlterField(
            model_name='option',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='sq_ft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='unit_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
