# Generated by Django 5.1 on 2024-08-29 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_alter_option_available_alter_option_layout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lists', to='agent.client'),
        ),
    ]
