# Generated by Django 5.1 on 2024-08-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_alter_list_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='sq_ft',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
