# Generated by Django 5.1 on 2024-09-04 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_list_link_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='link_url',
            new_name='uuid',
        ),
    ]
