# Generated by Django 5.1 on 2024-09-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0010_rename_link_url_list_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='flat_fee',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deal',
            name='lease_term',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='deal',
            name='rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deal',
            name='unit_no',
            field=models.CharField(max_length=255),
        ),
    ]
