# Generated by Django 5.1 on 2024-09-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0011_alter_deal_flat_fee_alter_deal_lease_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='flat_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
