# Generated by Django 5.1 on 2024-09-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0012_alter_deal_flat_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
