# Generated by Django 5.1 on 2024-09-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0013_alter_deal_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('not', 'Not Invoiced'), ('pend', 'Pending'), ('over', 'Overdue'), ('paid', 'Paid')], default='not', max_length=25),
        ),
    ]
