# Generated by Django 5.1 on 2024-09-10 22:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0014_deal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='deal_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
