# Generated by Django 5.1 on 2024-09-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0015_deal_deal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='overdue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
