# Generated by Django 5.1 on 2024-09-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0016_deal_invoice_date_deal_overdue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='lease_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
