# Generated by Django 5.1 on 2025-01-18 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('website', models.CharField(max_length=250)),
                ('market', models.CharField(choices=[('hou', 'Houston'), ('dfw', 'Dallas / Fort Worth'), ('atx', 'Austin')], default='hou', max_length=100)),
                ('neighborhood', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send', models.IntegerField(blank=True, default=0)),
                ('escort', models.IntegerField(blank=True, default=0)),
                ('flat_fee', models.IntegerField(blank=True, default=0)),
                ('updated_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='property.property')),
            ],
        ),
    ]
